### PR TITLE
Add poweroff option in the main menu

### PR DESCRIPTION
**Pull request by Wolfvak**
Also prevents the user from powering off after an AGB_FIRM title is rebooted, to prevent save loss.

### CODE REVIEW

**Comment by chaoskagami** [comment]
I honestly would've preferred this squashed since the first commit is broken alone, but hey, I probably would have pulled from your repo anyways. Merged. ;P

**Comment by Wolfvak** [comment]
Yeah, you can blame Notepad++ and the GitHub desktop client for that.
On an unrelated note, do emunand patches support rednand?

**Comment by chaoskagami** [comment]
Cakes' emunand patches are pretty generic and make use of the memory patch functionality to set up itself properly. It's suported redNAND for a long time now.

I didn't port over that chunk from luma (ARN at the time) because it isn't as simple with cakes - you can have multiple emunands, and it requires more checks than just reading config.dat.

You need to check if emunand.cake is enabled to determine if emunand is being used, which means loader needs to read the whole config.dat - I'm only reading the fragment of the header I need right now.  Aside from that, you read emunand_location from the config and figure out which emunand it is and whether it's rednand.

I'd recommend strings like 'Sys.', 'Em0.', 'Em1.'.

I didn't feel it was worth it to port over since most people with cakes now aren't noobs and know what NAND they're in. If you fix 3ds_injector and PR it, I'll merge it. I just didn't feel like the time investment for something that wouldn't help me personally.

**Comment by Wolfvak** [comment]
Oh, I won't differentiate between multiple emunands and emunand/rednand, just a simple indicator that you actually are in sysnand. But, there's lots of other stuff to do first, so I'll get working on them now

Also, I checked the patch's source and indeed it supports rednand (or rather, it supports gw emunand, because that's the one that needs a workaround)

**Comment by chaoskagami** [comment]
Aw. Well if we're just doing a sysnand check, all that's needed is checking whether the emunand cake is enabled.

Just submit a PR to 3ds_injector when you're done and I'll merge. I'll update the submodule in master afterwards.

Also one request - no ternary operators, please. They're nigh impossible to read.

**Comment by Wolfvak** [comment]
A simple if should suffice. And ternary operators aren't that hard to read, the problem is when you have one inside another one inside another one... and so on and so forth.
It becomes insane to even realize what the program's doing anymore.

**Comment by chaoskagami** [comment]
I prefer to avoid them altogether unless they improve readability. It's a slippery slope once you start using them.

Also, actually, screw it. You're part of the larger cakes ecosystem and you know what you're doing, so I'll just give you push to 3ds_injector. Remember: no forced pushes, and you want the choco branch, not master.

**Comment by Wolfvak** [comment]
Alright, thanks.
I'm working in patches right now, and I think I know why I couldn't get them to work: I was comparing against 0x50 FIRM instead of 0x49, like the nice idiot I am :P

**Comment by chaoskagami** [comment]
Happens to the best of us. I for one need more coffee now. :|

Also, maybe move the firm patch discussion back to mid-kid's issue tracker.

**Pull request merged**
